steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/refuge-survey-backend:latest', '-f', 'backend/Dockerfile', 'backend']

  # Push the backend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/refuge-survey-backend:latest']

  # Deploy backend container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'refuge-survey-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/refuge-survey-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/refuge-survey-frontend:latest', '-f', 'frontend/Dockerfile', 'frontend']

  # Push the frontend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/refuge-survey-frontend:latest']

  # Deploy frontend container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'refuge-survey-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/refuge-survey-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/refuge-survey-backend:latest'
  - 'gcr.io/$PROJECT_ID/refuge-survey-frontend:latest' 